[package]
name = "ch2-ownership-borrow"
version = "0.1.0"
authors = ["Tobias Ford <toby.ford@pobox.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
